const { bookMarkController } = require('../controllers/bookmarkController')
const { CommentPostController, repliesCommentPostController } = require('../controllers/commentComtroller')
const { dislikesPostController } = require('../controllers/dislikeController')
const { likePostController } = require('../controllers/likeController')
const { getAllPostController, postSinglePost, getUserPostController, getUserOnePostController, putSingleUserPostController, deleteSingleUserPostController, getOnePostController } = require('../controllers/postController')
const { verifyToken } = require('../middleware/jwtMiddleware')
const { createPostValidation } = require('../validator/createPostValidattion')

const route = require('express').Router()

exports.postRoute = route
    .get('/', getAllPostController)
    .get('/user-post', verifyToken, getUserPostController)
    .get('/user-post/:id', verifyToken, getUserOnePostController)
    .get('/:id', getOnePostController)
    .put('/user-post/:id', createPostValidation, verifyToken, putSingleUserPostController)
    .delete('/user-post/:id', verifyToken, deleteSingleUserPostController)
    .post('/', createPostValidation, verifyToken, postSinglePost)
    .post('/comments/:id', verifyToken,CommentPostController)
    .post('/comments/replies/:id', verifyToken,repliesCommentPostController)
    .post('/likes/:id', verifyToken,likePostController)
    .post('/dislikes/:id', verifyToken,dislikesPostController)
    .post('/bookmarks/:id', verifyToken,bookMarkController)